# Generated by Django 5.0.1 on 2024-12-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycare', '0002_checkmsghelp'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmsghelp',
            name='descrizione',
            field=models.TextField(default=''),
        ),
    ]
