# Generated by Django 5.0.1 on 2024-12-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycare', '0005_alter_checkmsghelp_data_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmsghelp',
            name='idgen',
            field=models.IntegerField(default=1),
        ),
    ]
