# Generated by Django 5.0.1 on 2024-12-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycare', '0006_checkmsghelp_idgen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmsghelp',
            name='data_check',
            field=models.DateTimeField(),
        ),
    ]
