# Generated by Django 5.1.3 on 2024-12-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycare', '0008_alter_checkmsghelp_data_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoremind',
            name='data_remind',
            field=models.DateField(),
        ),
    ]
