# Generated by Django 5.1.4 on 2024-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycare', '0009_alter_memoremind_data_remind'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timest', models.DateTimeField()),
                ('heartbeatavg', models.IntegerField()),
            ],
        ),
    ]
